name: Aygun Aliyeva Sundhordvik

roles:

  - Technical Project Manager

  - Software Developer

  - Technical Writer

  - Research Specialist

preferred:

  remote: true

  flexible: true

  part_time: true

salary:

  minimum_usd: 2500

languages:

  - English

  - Azerbaijani

  - Russian

  - Norwegian

  - Turkish

skills:

  python

  c#

  technical writing

  research

  git

  github

  ai tools

  project management

portfolio:

  linkedin: "https://www.linkedin.com/in/ayunalisun"

  github: "https://github.com/Ayka11"
